using System;
using System.Collections.Generic;

namespace MamMoi.Infrastructure.Models;

public partial class CareSchedule
{
    public int ScheduleId { get; set; }

    public int TreeId { get; set; }

    public int? WeatherId { get; set; }

    public string? TaskType { get; set; }

    public string? TaskName { get; set; }

    public string? Description { get; set; }

    public DateOnly? ScheduledDate { get; set; }

    public string? ScheduledTimeOfDay { get; set; }

    public int? EstimatedDurationMinutes { get; set; }

    public string? Status { get; set; }

    public DateTime? CompletedAt { get; set; }

    public int? CompletedByUserId { get; set; }

    public decimal? WaterAmountLiters { get; set; }

    public string? WaterSource { get; set; }

    public decimal? ActualWaterAmountLiters { get; set; }

    public string? FertilizerType { get; set; }

    public int? FertilizerAmountGrams { get; set; }

    public string? ApplicationMethod { get; set; }

    public decimal? ActualFertilizerAmountGrams { get; set; }

    public string? PruningType { get; set; }

    public string? PruningNotes { get; set; }

    public bool? IsAutoGenerated { get; set; }

    public string? GenerationReason { get; set; }

    public bool? GeneratedByAi { get; set; }

    public int? AirecommendationId { get; set; }

    public bool? WeatherAdjusted { get; set; }

    public DateOnly? OriginalScheduledDate { get; set; }

    public string? AdjustmentReason { get; set; }

    public decimal? ForecastRainAmountMm { get; set; }

    public decimal? ForecastTemperatureC { get; set; }

    public decimal? ForecastHumidityPct { get; set; }

    public string? Priority { get; set; }

    public bool? IsRecurring { get; set; }

    public string? RecurrencePattern { get; set; }

    public int? ParentScheduleId { get; set; }

    public bool? NotificationSent { get; set; }

    public DateTime? NotificationSentAt { get; set; }

    public string? Notes { get; set; }

    public string? CompletionNotes { get; set; }

    public string? PhotoUrls { get; set; }

    public int? ResultRating { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User? CompletedByUser { get; set; }

    public virtual ICollection<CareSchedule> InverseParentSchedule { get; set; } = new List<CareSchedule>();

    public virtual CareSchedule? ParentSchedule { get; set; }

    public virtual Tree Tree { get; set; } = null!;

    public virtual WeatherHistory? Weather { get; set; }
}
