-- ===== CareSchedules and ActivityLogs Seed Data Script =====
-- This script inserts sample data into CareSchedules and ActivityLogs tables
-- Run this script after schema.sql and insert.sql have been executed
-- Note: This script requires Users, Trees, and Gardens tables to have existing data

USE [MamMoi]
GO

-- Check if required tables exist before proceeding
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CareSchedules' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    PRINT 'ERROR: Table [dbo].[CareSchedules] does not exist. Please run schema.sql first!'
    RAISERROR('Required table [dbo].[CareSchedules] does not exist. Please run schema.sql first!', 16, 1)
    RETURN
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'ActivityLogs' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    PRINT 'ERROR: Table [dbo].[ActivityLogs] does not exist. Please run schema.sql first!'
    RAISERROR('Required table [dbo].[ActivityLogs] does not exist. Please run schema.sql first!', 16, 1)
    RETURN
END
GO

PRINT 'Starting CareSchedules and ActivityLogs seed data insertion...'
PRINT 'Note: Make sure Users, Trees, and Gardens tables have existing data.'
GO

-- ===== 1. CARE SCHEDULES =====
PRINT ''
PRINT 'Inserting CareSchedules...'
GO

-- Get Tree IDs and User IDs
DECLARE @Tree1ID INT;
DECLARE @Tree2ID INT;
DECLARE @Tree3ID INT;
DECLARE @Tree4ID INT;
DECLARE @Tree5ID INT;
DECLARE @Farmer1ID INT;
DECLARE @Farmer2ID INT;

-- Only get IDs if tables exist
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Trees' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    SELECT @Tree1ID = [TreeID] FROM [dbo].[Trees] WHERE [TreeName] = N'Cây Xoài 1';
    SELECT @Tree2ID = [TreeID] FROM [dbo].[Trees] WHERE [TreeName] = N'Cây Cam 1';
    SELECT @Tree3ID = [TreeID] FROM [dbo].[Trees] WHERE [TreeName] = N'Cây Ổi 1';
    SELECT @Tree4ID = [TreeID] FROM [dbo].[Trees] WHERE [TreeName] = N'Cây Cao Su 1';
    SELECT @Tree5ID = [TreeID] FROM [dbo].[Trees] WHERE [TreeName] = N'Cây Cà Phê 1';
END

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Users' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    SELECT @Farmer1ID = [UserID] FROM [dbo].[Users] WHERE [Email] = 'farmer1@mammoi.com';
    SELECT @Farmer2ID = [UserID] FROM [dbo].[Users] WHERE [Email] = 'farmer2@mammoi.com';
END

-- Care Schedule 1: Tưới nước cho Cây Xoài 1 (Pending)
IF @Tree1ID IS NOT NULL AND @Farmer1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[CareSchedules] WHERE [TreeID] = @Tree1ID AND [TaskType] = N'Tưới nước' AND [ScheduledDate] = CAST(GETDATE() AS DATE))
    BEGIN
        INSERT INTO [dbo].[CareSchedules] ([TreeID], [TaskType], [TaskName], [Description], [ScheduledDate], [ScheduledTimeOfDay], 
                                          [EstimatedDurationMinutes], [Status], [WaterAmountLiters], [WaterSource], 
                                          [Priority], [IsAutoGenerated], [CreatedAt])
        VALUES (@Tree1ID, N'Tưới nước', N'Tưới nước cho Cây Xoài 1', N'Tưới nước đều đặn để cây phát triển tốt', 
                CAST(GETDATE() AS DATE), N'Morning', 15, N'Pending', 2.0, N'Nước máy', N'Normal', 1, GETDATE());
        PRINT '  - Inserted: CareSchedule - Tưới nước (Cây Xoài 1)'
    END
END

-- Care Schedule 2: Bón phân cho Cây Cam 1 (Scheduled)
IF @Tree2ID IS NOT NULL AND @Farmer1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[CareSchedules] WHERE [TreeID] = @Tree2ID AND [TaskType] = N'Bón phân' AND [ScheduledDate] = DATEADD(DAY, 2, CAST(GETDATE() AS DATE)))
    BEGIN
        INSERT INTO [dbo].[CareSchedules] ([TreeID], [TaskType], [TaskName], [Description], [ScheduledDate], [ScheduledTimeOfDay], 
                                          [EstimatedDurationMinutes], [Status], [FertilizerType], [FertilizerAmountGrams], 
                                          [ApplicationMethod], [Priority], [IsAutoGenerated], [CreatedAt])
        VALUES (@Tree2ID, N'Bón phân', N'Bón phân cho Cây Cam 1', N'Bón phân NPK 16-16-8 để cây phát triển tốt', 
                DATEADD(DAY, 2, CAST(GETDATE() AS DATE)), N'Morning', 30, N'Scheduled', N'NPK 16-16-8', 100, 
                N'Rải xung quanh gốc', N'Normal', 1, GETDATE());
        PRINT '  - Inserted: CareSchedule - Bón phân (Cây Cam 1)'
    END
END

-- Care Schedule 3: Tưới nước cho Cây Ổi 1 (Completed)
IF @Tree3ID IS NOT NULL AND @Farmer1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[CareSchedules] WHERE [TreeID] = @Tree3ID AND [TaskType] = N'Tưới nước' AND [Status] = N'Completed')
    BEGIN
        INSERT INTO [dbo].[CareSchedules] ([TreeID], [TaskType], [TaskName], [Description], [ScheduledDate], [ScheduledTimeOfDay], 
                                          [EstimatedDurationMinutes], [Status], [CompletedAt], [CompletedByUserID], 
                                          [WaterAmountLiters], [ActualWaterAmountLiters], [WaterSource], 
                                          [CompletionNotes], [ResultRating], [Priority], [CreatedAt])
        VALUES (@Tree3ID, N'Tưới nước', N'Tưới nước cho Cây Ổi 1', N'Tưới nước đều đặn', 
                DATEADD(DAY, -1, CAST(GETDATE() AS DATE)), N'Morning', 15, N'Completed', DATEADD(DAY, -1, GETDATE()), @Farmer1ID,
                1.5, 1.5, N'Nước máy', N'Đã tưới đầy đủ, cây phát triển tốt', 5, N'Normal', DATEADD(DAY, -2, GETDATE()));
        PRINT '  - Inserted: CareSchedule - Tưới nước (Cây Ổi 1) - Completed'
    END
END

-- Care Schedule 4: Cắt tỉa cho Cây Cao Su 1 (Pending)
IF @Tree4ID IS NOT NULL AND @Farmer2ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[CareSchedules] WHERE [TreeID] = @Tree4ID AND [TaskType] = N'Cắt tỉa' AND [ScheduledDate] = DATEADD(DAY, 3, CAST(GETDATE() AS DATE)))
    BEGIN
        INSERT INTO [dbo].[CareSchedules] ([TreeID], [TaskType], [TaskName], [Description], [ScheduledDate], [ScheduledTimeOfDay], 
                                          [EstimatedDurationMinutes], [Status], [PruningType], [Priority], [IsAutoGenerated], [CreatedAt])
        VALUES (@Tree4ID, N'Cắt tỉa', N'Cắt tỉa cành cho Cây Cao Su 1', N'Cắt tỉa cành già, cành sâu bệnh', 
                DATEADD(DAY, 3, CAST(GETDATE() AS DATE)), N'Morning', 45, N'Pending', N'Tỉa cành', N'Normal', 1, GETDATE());
        PRINT '  - Inserted: CareSchedule - Cắt tỉa (Cây Cao Su 1)'
    END
END

-- Care Schedule 5: Bón phân cho Cây Cà Phê 1 (Scheduled)
IF @Tree5ID IS NOT NULL AND @Farmer2ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[CareSchedules] WHERE [TreeID] = @Tree5ID AND [TaskType] = N'Bón phân' AND [ScheduledDate] = DATEADD(DAY, 5, CAST(GETDATE() AS DATE)))
    BEGIN
        INSERT INTO [dbo].[CareSchedules] ([TreeID], [TaskType], [TaskName], [Description], [ScheduledDate], [ScheduledTimeOfDay], 
                                          [EstimatedDurationMinutes], [Status], [FertilizerType], [FertilizerAmountGrams], 
                                          [ApplicationMethod], [Priority], [IsAutoGenerated], [CreatedAt])
        VALUES (@Tree5ID, N'Bón phân', N'Bón phân cho Cây Cà Phê 1', N'Bón phân NPK để cây phát triển tốt', 
                DATEADD(DAY, 5, CAST(GETDATE() AS DATE)), N'Afternoon', 30, N'Scheduled', N'NPK 15-15-15', 150, 
                N'Rải xung quanh gốc', N'Normal', 1, GETDATE());
        PRINT '  - Inserted: CareSchedule - Bón phân (Cây Cà Phê 1)'
    END
END

-- Care Schedule 6: Tưới nước cho Cây Xoài 1 (Completed - past)
IF @Tree1ID IS NOT NULL AND @Farmer1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[CareSchedules] WHERE [TreeID] = @Tree1ID AND [TaskType] = N'Tưới nước' AND [Status] = N'Completed' AND [ScheduledDate] < CAST(GETDATE() AS DATE))
    BEGIN
        INSERT INTO [dbo].[CareSchedules] ([TreeID], [TaskType], [TaskName], [Description], [ScheduledDate], [ScheduledTimeOfDay], 
                                          [EstimatedDurationMinutes], [Status], [CompletedAt], [CompletedByUserID], 
                                          [WaterAmountLiters], [ActualWaterAmountLiters], [WaterSource], 
                                          [CompletionNotes], [ResultRating], [Priority], [CreatedAt])
        VALUES (@Tree1ID, N'Tưới nước', N'Tưới nước cho Cây Xoài 1', N'Tưới nước đều đặn', 
                DATEADD(DAY, -3, CAST(GETDATE() AS DATE)), N'Morning', 15, N'Completed', DATEADD(DAY, -3, DATEADD(HOUR, 8, GETDATE())), @Farmer1ID,
                2.0, 2.0, N'Nước máy', N'Đã tưới đầy đủ', 4, N'Normal', DATEADD(DAY, -4, GETDATE()));
        PRINT '  - Inserted: CareSchedule - Tưới nước (Cây Xoài 1) - Completed (Past)'
    END
END

-- Care Schedule 7: Kiểm tra sức khỏe cho Cây Cam 1 (Pending - High Priority)
IF @Tree2ID IS NOT NULL AND @Farmer1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[CareSchedules] WHERE [TreeID] = @Tree2ID AND [TaskType] = N'Kiểm tra sức khỏe' AND [Priority] = N'High')
    BEGIN
        INSERT INTO [dbo].[CareSchedules] ([TreeID], [TaskType], [TaskName], [Description], [ScheduledDate], [ScheduledTimeOfDay], 
                                          [EstimatedDurationMinutes], [Status], [Priority], [Notes], [IsAutoGenerated], [CreatedAt])
        VALUES (@Tree2ID, N'Kiểm tra sức khỏe', N'Kiểm tra sức khỏe cho Cây Cam 1', N'Kiểm tra lá, thân, quả xem có dấu hiệu sâu bệnh không', 
                DATEADD(DAY, 1, CAST(GETDATE() AS DATE)), N'Morning', 20, N'Pending', N'High', N'Cần kiểm tra kỹ vì có dấu hiệu lá vàng', 0, GETDATE());
        PRINT '  - Inserted: CareSchedule - Kiểm tra sức khỏe (Cây Cam 1) - High Priority'
    END
END

-- Care Schedule 8: Recurring task - Tưới nước định kỳ cho Cây Ổi 1
IF @Tree3ID IS NOT NULL AND @Farmer1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[CareSchedules] WHERE [TreeID] = @Tree3ID AND [IsRecurring] = 1 AND [TaskType] = N'Tưới nước')
    BEGIN
        INSERT INTO [dbo].[CareSchedules] ([TreeID], [TaskType], [TaskName], [Description], [ScheduledDate], [ScheduledTimeOfDay], 
                                          [EstimatedDurationMinutes], [Status], [WaterAmountLiters], [WaterSource], 
                                          [Priority], [IsRecurring], [RecurrencePattern], [IsAutoGenerated], [CreatedAt])
        VALUES (@Tree3ID, N'Tưới nước', N'Tưới nước định kỳ cho Cây Ổi 1', N'Tưới nước mỗi 2 ngày', 
                DATEADD(DAY, 2, CAST(GETDATE() AS DATE)), N'Morning', 15, N'Scheduled', 1.5, N'Nước máy', 
                N'Normal', 1, N'Every 2 days', 1, GETDATE());
        PRINT '  - Inserted: CareSchedule - Tưới nước định kỳ (Cây Ổi 1)'
    END
END
GO

-- ===== 2. ACTIVITY LOGS =====
PRINT ''
PRINT 'Inserting ActivityLogs...'
GO

-- Get User IDs and Tree IDs
DECLARE @Farmer1ID INT;
DECLARE @Farmer2ID INT;
DECLARE @SystemAdminID INT;
DECLARE @BusinessAdminID INT;
DECLARE @Tree1ID INT;
DECLARE @Tree2ID INT;
DECLARE @Tree3ID INT;
DECLARE @Tree4ID INT;
DECLARE @Garden1ID INT;
DECLARE @CareSchedule1ID INT;
DECLARE @CareSchedule3ID INT;

-- Only get IDs if tables exist
IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Users' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    SELECT @Farmer1ID = [UserID] FROM [dbo].[Users] WHERE [Email] = 'farmer1@mammoi.com';
    SELECT @Farmer2ID = [UserID] FROM [dbo].[Users] WHERE [Email] = 'farmer2@mammoi.com';
    SELECT @SystemAdminID = [UserID] FROM [dbo].[Users] WHERE [Email] = 'systemadmin@mammoi.com';
    SELECT @BusinessAdminID = [UserID] FROM [dbo].[Users] WHERE [Email] = 'businessadmin@mammoi.com';
END

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Trees' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    SELECT @Tree1ID = [TreeID] FROM [dbo].[Trees] WHERE [TreeName] = N'Cây Xoài 1';
    SELECT @Tree2ID = [TreeID] FROM [dbo].[Trees] WHERE [TreeName] = N'Cây Cam 1';
    SELECT @Tree3ID = [TreeID] FROM [dbo].[Trees] WHERE [TreeName] = N'Cây Ổi 1';
    SELECT @Tree4ID = [TreeID] FROM [dbo].[Trees] WHERE [TreeName] = N'Cây Cao Su 1';
END

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'Gardens' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    SELECT @Garden1ID = [GardenID] FROM [dbo].[Gardens] WHERE [Name] = N'Vườn Cây Ăn Quả Nhà Tôi';
END

IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CareSchedules' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    SELECT TOP 1 @CareSchedule1ID = [ScheduleID] FROM [dbo].[CareSchedules] WHERE [TreeID] = @Tree1ID AND [TaskType] = N'Tưới nước' ORDER BY [CreatedAt] DESC;
    SELECT TOP 1 @CareSchedule3ID = [ScheduleID] FROM [dbo].[CareSchedules] WHERE [TreeID] = @Tree3ID AND [Status] = N'Completed';
END

-- Activity Log 1: User đăng nhập
IF @Farmer1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'Login' AND [CreatedAt] > DATEADD(HOUR, -1, GETDATE()))
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [ActivityType], [ActivityDescription], [UserAgent], [CreatedAt])
        VALUES (@Farmer1ID, N'Login', N'Người dùng đăng nhập vào hệ thống', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', GETDATE());
        PRINT '  - Inserted: ActivityLog - Login (Farmer1)'
    END
END

-- Activity Log 2: Tạo vườn
IF @Farmer1ID IS NOT NULL AND @Garden1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'Create' AND [EntityType] = N'Garden' AND [EntityID] = @Garden1ID)
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [ActivityType], [ActivityDescription], [EntityType], [EntityID], 
                                         [ActionData], [CreatedAt])
        VALUES (@Farmer1ID, N'Create', N'Tạo vườn mới: Vườn Cây Ăn Quả Nhà Tôi', N'Garden', @Garden1ID, 
                N'{"GardenName": "Vườn Cây Ăn Quả Nhà Tôi", "Location": "123 Đường ABC, Quận 1, TP.HCM"}', DATEADD(DAY, -30, GETDATE()));
        PRINT '  - Inserted: ActivityLog - Create Garden'
    END
END

-- Activity Log 3: Thêm cây
IF @Farmer1ID IS NOT NULL AND @Tree1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'Create' AND [EntityType] = N'Tree' AND [EntityID] = @Tree1ID)
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [TreeID], [ActivityType], [ActivityDescription], [EntityType], [EntityID], 
                                         [ActionData], [CreatedAt])
        VALUES (@Farmer1ID, @Tree1ID, N'Create', N'Thêm cây mới: Cây Xoài 1', N'Tree', @Tree1ID, 
                N'{"TreeName": "Cây Xoài 1", "TreeCode": "TREE001", "Location": "Góc trái vườn"}', DATEADD(DAY, -25, GETDATE()));
        PRINT '  - Inserted: ActivityLog - Create Tree (Cây Xoài 1)'
    END
END

-- Activity Log 4: Cập nhật thông tin cây
IF @Farmer1ID IS NOT NULL AND @Tree1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'Update' AND [EntityType] = N'Tree' AND [EntityID] = @Tree1ID AND [CreatedAt] > DATEADD(DAY, -20, GETDATE()))
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [TreeID], [ActivityType], [ActivityDescription], [EntityType], [EntityID], 
                                         [ActionData], [OldValue], [NewValue], [CreatedAt])
        VALUES (@Farmer1ID, @Tree1ID, N'Update', N'Cập nhật thông tin cây: Cây Xoài 1', N'Tree', @Tree1ID, 
                N'{"Field": "Notes"}', N'{"Notes": "Cây mới trồng"}', 
                N'{"Notes": "Cây mới trồng, cần chăm sóc kỹ"}', DATEADD(DAY, -20, GETDATE()));
        PRINT '  - Inserted: ActivityLog - Update Tree (Cây Xoài 1)'
    END
END

-- Activity Log 5: Hoàn thành task chăm sóc
IF @Farmer1ID IS NOT NULL AND @Tree3ID IS NOT NULL AND @CareSchedule3ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'Complete' AND [EntityType] = N'CareSchedule' AND [EntityID] = @CareSchedule3ID)
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [TreeID], [ActivityType], [ActivityDescription], [EntityType], [EntityID], 
                                         [ActionData], [CreatedAt])
        VALUES (@Farmer1ID, @Tree3ID, N'Complete', N'Hoàn thành task: Tưới nước cho Cây Ổi 1', N'CareSchedule', @CareSchedule3ID, 
                N'{"TaskType": "Tưới nước", "ActualWaterAmount": 1.5, "Rating": 5}', DATEADD(DAY, -1, GETDATE()));
        PRINT '  - Inserted: ActivityLog - Complete CareSchedule'
    END
END

-- Activity Log 6: Tạo lịch chăm sóc
IF @Farmer1ID IS NOT NULL AND @Tree1ID IS NOT NULL AND @CareSchedule1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'Create' AND [EntityType] = N'CareSchedule' AND [EntityID] = @CareSchedule1ID)
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [TreeID], [ActivityType], [ActivityDescription], [EntityType], [EntityID], 
                                         [ActionData], [CreatedAt])
        VALUES (@Farmer1ID, @Tree1ID, N'Create', N'Tạo lịch chăm sóc: Tưới nước cho Cây Xoài 1', N'CareSchedule', @CareSchedule1ID, 
                N'{"TaskType": "Tưới nước", "ScheduledDate": "' + CAST(CAST(GETDATE() AS DATE) AS NVARCHAR(50)) + '", "IsAutoGenerated": true}', GETDATE());
        PRINT '  - Inserted: ActivityLog - Create CareSchedule'
    END
END

-- Activity Log 7: Xem chi tiết cây
IF @Farmer1ID IS NOT NULL AND @Tree2ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'View' AND [EntityType] = N'Tree' AND [EntityID] = @Tree2ID AND [CreatedAt] > DATEADD(HOUR, -2, GETDATE()))
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [TreeID], [ActivityType], [ActivityDescription], [EntityType], [EntityID], 
                                         [CreatedAt])
        VALUES (@Farmer1ID, @Tree2ID, N'View', N'Xem chi tiết cây: Cây Cam 1', N'Tree', @Tree2ID, DATEADD(HOUR, -1, GETDATE()));
        PRINT '  - Inserted: ActivityLog - View Tree (Cây Cam 1)'
    END
END

-- Activity Log 8: System Admin - Quản lý hệ thống
IF @SystemAdminID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @SystemAdminID AND [ActivityType] = N'SystemAction' AND [CreatedAt] > DATEADD(DAY, -1, GETDATE()))
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [ActivityType], [ActivityDescription], [EntityType], 
                                         [ActionData], [CreatedAt])
        VALUES (@SystemAdminID, N'SystemAction', N'Thực hiện bảo trì hệ thống', N'System', 
                N'{"Action": "SystemMaintenance", "Duration": "30 minutes"}', DATEADD(HOUR, -12, GETDATE()));
        PRINT '  - Inserted: ActivityLog - SystemAction (SystemAdmin)'
    END
END

-- Activity Log 9: Business Admin - Quản lý người dùng
IF @BusinessAdminID IS NOT NULL AND @Farmer1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @BusinessAdminID AND [ActivityType] = N'Update' AND [EntityType] = N'User' AND [EntityID] = @Farmer1ID)
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [ActivityType], [ActivityDescription], [EntityType], [EntityID], 
                                         [ActionData], [CreatedAt])
        VALUES (@BusinessAdminID, N'Update', N'Cập nhật thông tin người dùng', N'User', @Farmer1ID, 
                N'{"Field": "IsActive", "Value": true}', DATEADD(DAY, -5, GETDATE()));
        PRINT '  - Inserted: ActivityLog - Update User (BusinessAdmin)'
    END
END

-- Activity Log 10: Upload ảnh cây
IF @Farmer1ID IS NOT NULL AND @Tree1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'Upload' AND [EntityType] = N'TreeImage' AND [TreeID] = @Tree1ID)
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [TreeID], [ActivityType], [ActivityDescription], [EntityType], 
                                         [ActionData], [CreatedAt])
        VALUES (@Farmer1ID, @Tree1ID, N'Upload', N'Upload ảnh cho cây: Cây Xoài 1', N'TreeImage', 
                N'{"ImageCount": 1, "ImageType": "TreeHealth"}', DATEADD(DAY, -15, GETDATE()));
        PRINT '  - Inserted: ActivityLog - Upload Tree Image'
    END
END

-- Activity Log 11: Tìm kiếm cây
IF @Farmer1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'Search' AND [CreatedAt] > DATEADD(HOUR, -3, GETDATE()))
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [ActivityType], [ActivityDescription], 
                                         [ActionData], [CreatedAt])
        VALUES (@Farmer1ID, N'Search', N'Tìm kiếm cây trong vườn', 
                N'{"SearchTerm": "Xoài", "Results": 1}', DATEADD(HOUR, -2, GETDATE()));
        PRINT '  - Inserted: ActivityLog - Search'
    END
END

-- Activity Log 12: Cập nhật lịch chăm sóc
IF @Farmer1ID IS NOT NULL AND @CareSchedule1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'Update' AND [EntityType] = N'CareSchedule' AND [EntityID] = @CareSchedule1ID)
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [TreeID], [ActivityType], [ActivityDescription], [EntityType], [EntityID], 
                                         [ActionData], [OldValue], [NewValue], [CreatedAt])
        VALUES (@Farmer1ID, @Tree1ID, N'Update', N'Cập nhật lịch chăm sóc: Thay đổi thời gian tưới nước', N'CareSchedule', @CareSchedule1ID, 
                N'{"Field": "ScheduledTimeOfDay"}', N'{"ScheduledTimeOfDay": "Afternoon"}', N'{"ScheduledTimeOfDay": "Morning"}', DATEADD(HOUR, -5, GETDATE()));
        PRINT '  - Inserted: ActivityLog - Update CareSchedule'
    END
END

-- Activity Log 13: Farmer 2 - Thêm cây
IF @Farmer2ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer2ID AND [ActivityType] = N'Create' AND [EntityType] = N'Tree')
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [TreeID], [ActivityType], [ActivityDescription], [EntityType], [EntityID], 
                                         [ActionData], [CreatedAt])
        VALUES (@Farmer2ID, @Tree4ID, N'Create', N'Thêm cây mới: Cây Cao Su 1', N'Tree', @Tree4ID, 
                N'{"TreeName": "Cây Cao Su 1", "TreeCode": "TREE004"}', DATEADD(DAY, -40, GETDATE()));
        PRINT '  - Inserted: ActivityLog - Create Tree (Farmer2)'
    END
END

-- Activity Log 14: Đổi mật khẩu
IF @Farmer1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'PasswordChange')
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [ActivityType], [ActivityDescription], [EntityType], 
                                         [ActionData], [CreatedAt])
        VALUES (@Farmer1ID, N'PasswordChange', N'Đổi mật khẩu tài khoản', N'User', 
                N'{"ChangedAt": "' + CAST(GETDATE() AS NVARCHAR(50)) + '"}', DATEADD(DAY, -7, GETDATE()));
        PRINT '  - Inserted: ActivityLog - Password Change'
    END
END

-- Activity Log 15: Đăng xuất
IF @Farmer1ID IS NOT NULL
BEGIN
    IF NOT EXISTS (SELECT 1 FROM [dbo].[ActivityLogs] WHERE [UserID] = @Farmer1ID AND [ActivityType] = N'Logout' AND [CreatedAt] > DATEADD(HOUR, -24, GETDATE()))
    BEGIN
        INSERT INTO [dbo].[ActivityLogs] ([UserID], [ActivityType], [ActivityDescription], [UserAgent], [CreatedAt])
        VALUES (@Farmer1ID, N'Logout', N'Người dùng đăng xuất khỏi hệ thống', N'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', DATEADD(HOUR, -6, GETDATE()));
        PRINT '  - Inserted: ActivityLog - Logout (Farmer1)'
    END
END
GO

PRINT ''
PRINT '========================================'
PRINT 'CareSchedules and ActivityLogs seed data insertion completed!'
PRINT '========================================'
PRINT ''
PRINT 'Summary:'
PRINT '  - CareSchedules: 8 records'
PRINT '    * Tưới nước (Pending, Completed)'
PRINT '    * Bón phân (Scheduled)'
PRINT '    * Cắt tỉa (Pending)'
PRINT '    * Kiểm tra sức khỏe (Pending - High Priority)'
PRINT '    * Tưới nước định kỳ (Recurring)'
PRINT ''
PRINT '  - ActivityLogs: 15 records'
PRINT '    * Login, Logout'
PRINT '    * Create (Garden, Tree, CareSchedule)'
PRINT '    * Update (Tree, CareSchedule, User)'
PRINT '    * Complete (CareSchedule)'
PRINT '    * View (Tree)'
PRINT '    * Upload (TreeImage)'
PRINT '    * Search'
PRINT '    * PasswordChange'
PRINT '    * SystemAction'
PRINT ''
GO

