<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTO\**" />
    <Compile Remove="Entities\**" />
    <EmbeddedResource Remove="DTO\**" />
    <EmbeddedResource Remove="Entities\**" />
    <None Remove="DTO\**" />
    <None Remove="Entities\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\" />
  </ItemGroup>

</Project>
