using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MamMoi.Api.Infrastructure.Models;

public partial class CareSchedules
{
    [Key]
    public int ScheduleID { get; set; }

    public int TreeID { get; set; }

    public int? WeatherID { get; set; }

    [StringLength(50)]
    public string? TaskType { get; set; }

    [StringLength(200)]
    public string? TaskName { get; set; }

    [StringLength(1000)]
    public string? Description { get; set; }

    public DateOnly? ScheduledDate { get; set; }

    [StringLength(20)]
    public string? ScheduledTimeOfDay { get; set; }

    public int? EstimatedDurationMinutes { get; set; }

    [StringLength(50)]
    public string? Status { get; set; }

    [Precision(0)]
    public DateTime? CompletedAt { get; set; }

    public int? CompletedByUserID { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? WaterAmountLiters { get; set; }

    [StringLength(50)]
    public string? WaterSource { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? ActualWaterAmountLiters { get; set; }

    [StringLength(100)]
    public string? FertilizerType { get; set; }

    public int? FertilizerAmountGrams { get; set; }

    [StringLength(100)]
    public string? ApplicationMethod { get; set; }

    [Column(TypeName = "decimal(6, 2)")]
    public decimal? ActualFertilizerAmountGrams { get; set; }

    [StringLength(50)]
    public string? PruningType { get; set; }

    [StringLength(500)]
    public string? PruningNotes { get; set; }

    public bool? IsAutoGenerated { get; set; }

    [StringLength(500)]
    public string? GenerationReason { get; set; }

    public bool? GeneratedByAI { get; set; }

    public int? AIRecommendationID { get; set; }

    public bool? WeatherAdjusted { get; set; }

    public DateOnly? OriginalScheduledDate { get; set; }

    [StringLength(500)]
    public string? AdjustmentReason { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? ForecastRainAmountMm { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? ForecastTemperatureC { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? ForecastHumidityPct { get; set; }

    [StringLength(20)]
    public string? Priority { get; set; }

    public bool? IsRecurring { get; set; }

    [StringLength(100)]
    public string? RecurrencePattern { get; set; }

    public int? ParentScheduleID { get; set; }

    public bool? NotificationSent { get; set; }

    [Precision(0)]
    public DateTime? NotificationSentAt { get; set; }

    [StringLength(1000)]
    public string? Notes { get; set; }

    [StringLength(1000)]
    public string? CompletionNotes { get; set; }

    public string? PhotoUrls { get; set; }

    public int? ResultRating { get; set; }

    [Precision(0)]
    public DateTime CreatedAt { get; set; }

    [Precision(0)]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("CompletedByUserID")]
    [InverseProperty("CareSchedules")]
    public virtual Users? CompletedByUser { get; set; }

    [InverseProperty("ParentSchedule")]
    public virtual ICollection<CareSchedules> InverseParentSchedule { get; set; } = new List<CareSchedules>();

    [ForeignKey("ParentScheduleID")]
    [InverseProperty("InverseParentSchedule")]
    public virtual CareSchedules? ParentSchedule { get; set; }

    [ForeignKey("TreeID")]
    [InverseProperty("CareSchedules")]
    public virtual Trees Tree { get; set; } = null!;

    [ForeignKey("WeatherID")]
    [InverseProperty("CareSchedules")]
    public virtual WeatherHistories? Weather { get; set; }
}
